apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-api-deploy
  namespace: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-api
  template:
    metadata:
      labels:
        app: accounts-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - micro
      containers:
      - name: accounts-api
        image: othbel/accounts-api:1.0.0
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: micro-env
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: micro-env
                key: SPRING_CONFIG_IMPORT
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: micro-env
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_ZIPKIN_BASEURL
            valueFrom:
              configMapKeyRef:
                name: micro-env
                key: SPRING_ZIPKIN_BASEURL
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
