apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: micro
spec:
  type: ClusterIP
  selector:
    app: accounts-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
