apiVersion: v1
kind: ConfigMap
metadata:
  name: tools-env
  namespace: tools
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "eureka-server-service.tools:8070" # accounts/cards/loans
  SPRING_CONFIG_IMPORT: "config-server-service.tools:8071" # accounts/cards/eureka/gateway/loans
  SPRING_PROFILES_ACTIVE: "prod" # accounts/cards/configserver!!/loans
  SPRING_ZIPKIN_BASEURL: "zipkin-service.tools:9411" # accounts/cards/configserver/eureka/gateway/loans

