apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  namespace: micro
spec:
  # type: ExternalName
  # externalName: eureka-server-service.micro.svc.cluster.local
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
  - port: 8070
    targetPort: 8070
