apiVersion: v1
kind: Service
metadata:
  name: loans-api-service
  namespace: micro
spec:
  type: ClusterIP
  selector:
    app: loans-api
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
